### ISSUE TITLE
Ineficiente

### ISSUE THREAD

**Issue by CesarZarco** [CesarZarco/lima_latin_sqr#3]
En (allsqr.py) la funcion all_squares_permutation() es en extremo ineficiente, no servirá para calcular los cuadrados latinos de 5x5

**Comment by jcar2905** [comment]
Agregue una función más eficiente, sin embargo está genera todos los cuadrados latinos de orden n, busquemos si existe una solución que nos permita verificar el resultado del problema sin usar todos los cuadrados latinos

**Comment by jcar2905** [comment]
Agregue una función más eficiente, sin embargo está genera todos los cuadrados latinos de orden n, busquemos si existe una solución que nos permita verificar el resultado del problema sin usar todos los cuadrados latinos
