### ISSUE TITLE
Función en alpha.py no esta definida

### ISSUE THREAD

**Issue by jcar2905** [CesarZarco/lima_latin_sqr#4]
Al importar el paquete a un codigó de python aparece el siguiente error:

NameError: name 'generar_todos_los_cuadrados_latinos' is not defined

**Comment by CesarZarco** [comment]
El nombre de la funcion es 'generar_todos_los_cuadrados_latinos_letras', sin embargo la funcion ahora ya no se encuentra, ya que no es practica para el proposito del proyecto
